//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawPaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int PersonnelId { get; set; }
        public string PersonnelName { get; set; }
        public int PersonnelTypeId { get; set; }
        public System.DateTime WorkingFrom { get; set; }
    }
}
